-- QUERY 3 (THIN) — BU KPI Split with 1σ Spike Flags (Section 2.2)
-- Returns ~6 rows. Reads from V_HWL_HR view.
-- Caller must SET WEEK_START / WEEK_END session variables before executing.

WITH mp_dedup AS (
    SELECT DISTINCT EMPLOYEE_ID, OBR_SITE_GROUP, ENTITY_EVENT_DATE, DAILY_MISSED_PUNCHES
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR
    WHERE DAILY_MISSED_PUNCHES > 0
),
weekly_baseline_agg AS (
    SELECT 
        'Network' AS GROUP_NAME,
        SUM(TOTAL_ACTIONS) AS TOTAL_ACTIONS,
        SUM(BUCKET_B_ACTIONS) AS BUCKET_B_ACTIONS,
        (SUM(BUCKET_B_ACTIONS) / NULLIF(SUM(TOTAL_ACTIONS), 0)) * 100 AS MEAN_13WK_DEFECT_RATE,
        AVG(SD_13WK_DEFECT_RATE) AS SD_13WK_DEFECT_RATE
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_WEEKLY_SITE_METRICS
    WHERE REPORT_WEEK = DATE_TRUNC('WEEK', $WEEK_START)
    
    UNION ALL
    
    SELECT 
        OBR_SITE_GROUP AS GROUP_NAME,
        SUM(TOTAL_ACTIONS) AS TOTAL_ACTIONS,
        SUM(BUCKET_B_ACTIONS) AS BUCKET_B_ACTIONS,
        (SUM(BUCKET_B_ACTIONS) / NULLIF(SUM(TOTAL_ACTIONS), 0)) * 100 AS MEAN_13WK_DEFECT_RATE,
        AVG(SD_13WK_DEFECT_RATE) AS SD_13WK_DEFECT_RATE
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_WEEKLY_SITE_METRICS
    WHERE REPORT_WEEK = DATE_TRUNC('WEEK', $WEEK_START)
    GROUP BY OBR_SITE_GROUP
    
    UNION ALL
    
    SELECT 'HRSS' AS GROUP_NAME, NULL, NULL, NULL, NULL
),
current_week_bu AS (
    SELECT
        grp.GROUP_NAME,
        COUNT(h.EMPLOYEE_ID)                                                                AS ACTION_VOLUME,
        SUM(CASE WHEN h.BUCKET_B THEN 1 ELSE 0 END)                                        AS BUCKET_B_COUNT,
        ROUND(SUM(CASE WHEN h.BUCKET_B THEN 1 ELSE 0 END)/COUNT(h.EMPLOYEE_ID)*100,1)      AS DEFECT_PCT,
        COUNT(DISTINCT m.EMPLOYEE_ID||'|'||CAST(m.ENTITY_EVENT_DATE AS VARCHAR))            AS MISSED_PUNCH_COUNT,
        ROUND(COUNT(DISTINCT m.EMPLOYEE_ID||'|'||CAST(m.ENTITY_EVENT_DATE AS VARCHAR))/COUNT(h.EMPLOYEE_ID)*100,1) AS MISSED_PUNCH_PCT,
        SUM(CASE WHEN h.ENTITY_TYPE='Historical Correction' THEN 1 ELSE 0 END)             AS HIST_CORR_COUNT,
        ROUND(SUM(CASE WHEN h.ENTITY_TYPE='Historical Correction' THEN 1 ELSE 0 END)/COUNT(h.EMPLOYEE_ID)*100,1) AS HIST_CORR_PCT,
        COUNT(DISTINCT h.EMPLOYEE_ID)                                                       AS UNIQUE_TMS
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR h
    LEFT JOIN mp_dedup m ON m.EMPLOYEE_ID=h.EMPLOYEE_ID AND m.ENTITY_EVENT_DATE=h.ENTITY_EVENT_DATE
    JOIN (
        SELECT 'Network' AS GROUP_NAME,NULL AS FILTER_FIELD,NULL AS FILTER_VALUE
        UNION ALL SELECT 'FC','OBR_SITE_GROUP','FC' UNION ALL SELECT 'Rx','OBR_SITE_GROUP','Rx'
        UNION ALL SELECT 'CC','OBR_SITE_GROUP','CC' UNION ALL SELECT 'CVC','OBR_SITE_GROUP','CVC'
        UNION ALL SELECT 'HRSS','OBR_ACTOR_GROUP','HRSS'
    ) grp ON (grp.FILTER_VALUE IS NULL OR (grp.FILTER_FIELD='OBR_SITE_GROUP' AND h.OBR_SITE_GROUP=grp.FILTER_VALUE) OR (grp.FILTER_FIELD='OBR_ACTOR_GROUP' AND h.OBR_ACTOR_GROUP=grp.FILTER_VALUE))
    GROUP BY grp.GROUP_NAME
)
SELECT 
    c.*,
    COALESCE(b.MEAN_13WK_DEFECT_RATE, 0) AS MEAN_13WK_DEFECT_RATE,
    COALESCE(b.SD_13WK_DEFECT_RATE, 0) AS SD_13WK_DEFECT_RATE,
    (COALESCE(b.MEAN_13WK_DEFECT_RATE, 0) + COALESCE(b.SD_13WK_DEFECT_RATE, 0)) AS UCL_13WK_DEFECT_RATE,
    CASE WHEN c.DEFECT_PCT > (COALESCE(b.MEAN_13WK_DEFECT_RATE, 0) + COALESCE(b.SD_13WK_DEFECT_RATE, 0)) THEN TRUE ELSE FALSE END AS IS_RED_SPIKE
FROM current_week_bu c
LEFT JOIN weekly_baseline_agg b ON c.GROUP_NAME = b.GROUP_NAME
ORDER BY ARRAY_POSITION(ARRAY_CONSTRUCT('Network','FC','Rx','CC','CVC','HRSS'),c.GROUP_NAME::VARIANT);
