-- QUERY 4 (THIN) — Top Paycode Categories by BU (Sections 2.3–2.7)
-- Returns ~80 rows. Reads from V_HWL_HR view.
-- Caller must SET WEEK_START / WEEK_END session variables before executing.

SELECT COALESCE(OBR_SITE_GROUP, OBR_ACTOR_GROUP) AS BU_OR_GROUP, PAYCODE_CATEGORY, ENTITY_TYPE,
    COUNT(*) AS ACTION_COUNT, ROUND(COUNT(*)/60.0,1) AS ESTIMATED_HRS
FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR
WHERE BUCKET_B=TRUE OR ENTITY_TYPE='Pay Code Edit'
GROUP BY COALESCE(OBR_SITE_GROUP, OBR_ACTOR_GROUP), PAYCODE_CATEGORY, ENTITY_TYPE
ORDER BY BU_OR_GROUP, ACTION_COUNT DESC;
