-- QUERY 6 (THIN) — Site-Level Defect Stats with 1σ Spike Flags (Section 5)
-- Returns ~50 rows. Reads from V_HWL_HR view.
-- v2.0 DPMO: × 1,000,000 (PRD §5.1)
-- Caller must SET WEEK_START / WEEK_END session variables before executing.

WITH mp_dedup AS (
    SELECT DISTINCT EMPLOYEE_ID, ENTITY_EVENT_DATE, BUILDING_LOCATION, DAILY_MISSED_PUNCHES
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR
    WHERE DAILY_MISSED_PUNCHES > 0
),
site_mp AS (
    SELECT BUILDING_LOCATION, SUM(DAILY_MISSED_PUNCHES) AS MISSED_PUNCH_COUNT
    FROM mp_dedup
    GROUP BY BUILDING_LOCATION
),
site_stats AS (
    SELECT h.BUILDING_LOCATION, h.OBR_SITE_GROUP,
        COUNT(*) AS TOTAL_ACTIONS,
        SUM(CASE WHEN h.BUCKET_B THEN 1 ELSE 0 END) AS BUCKET_B_COUNT,
        COUNT(DISTINCT h.EMPLOYEE_ID) AS UNIQUE_TMS
    FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR h
    GROUP BY h.BUILDING_LOCATION, h.OBR_SITE_GROUP
    HAVING COUNT(DISTINCT h.EMPLOYEE_ID) > 5
),
current_week_metrics AS (
    SELECT s.BUILDING_LOCATION, s.OBR_SITE_GROUP, s.TOTAL_ACTIONS, s.BUCKET_B_COUNT, s.UNIQUE_TMS,
        COALESCE(m.MISSED_PUNCH_COUNT, 0) AS MISSED_PUNCH_COUNT,
        ROUND(COALESCE(m.MISSED_PUNCH_COUNT, 0)/NULLIF(s.UNIQUE_TMS,0)*100,1) AS MP_PER_100_TMS,
        ROUND(s.BUCKET_B_COUNT/NULLIF(s.UNIQUE_TMS*20,0)*1000000,2) AS DPMO,
        (s.BUCKET_B_COUNT / NULLIF(s.TOTAL_ACTIONS, 0)) * 100 AS DEFECT_RATE_PCT
    FROM site_stats s
    LEFT JOIN site_mp m ON s.BUILDING_LOCATION = m.BUILDING_LOCATION
)
SELECT 
    c.*,
    v.MEAN_13WK_DEFECT_RATE,
    v.SD_13WK_DEFECT_RATE,
    (v.MEAN_13WK_DEFECT_RATE + v.SD_13WK_DEFECT_RATE) AS UCL_13WK_DEFECT_RATE,
    CASE WHEN c.DEFECT_RATE_PCT > (v.MEAN_13WK_DEFECT_RATE + v.SD_13WK_DEFECT_RATE) THEN TRUE ELSE FALSE END AS IS_RED_SPIKE
FROM current_week_metrics c
LEFT JOIN EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_WEEKLY_SITE_METRICS v
       ON c.BUILDING_LOCATION = v.BUILDING_LOCATION 
      AND v.REPORT_WEEK = DATE_TRUNC('WEEK', $WEEK_START)
ORDER BY c.DPMO DESC;
