-- QUERY 7 (THIN) — Comment Compliance by BU (Section 6)
-- Returns ~5 rows. Reads from V_HWL_HR view.
-- Caller must SET WEEK_START / WEEK_END session variables before executing.

SELECT COALESCE(OBR_SITE_GROUP, 'Network') AS OBR_SITE_GROUP,
    COUNT(*) AS HIGH_RISK_ACTIONS,
    SUM(HAS_COMMENT) AS COMMENTS_ADDED,
    ROUND(SUM(HAS_COMMENT)/COUNT(*)*100,1) AS DOCUMENTATION_RATE_PCT
FROM EDLDB.PEOPLE_ANALYTICS_SANDBOX.V_HWL_HR
WHERE HIGH_RISK_REWORK=TRUE
GROUP BY ROLLUP(OBR_SITE_GROUP)
ORDER BY OBR_SITE_GROUP;
